;;; score-test.el --- the ordinal head, and the claims it is allowed to make -*- lexical-binding: t; -*-

;;; Commentary:

;; Score asserts something the other two primitives do not: that the levels are
;; ORDERED, and that knowing it buys something.  Three groups of checks, in the
;; order a reader should want them:
;;
;;   1. The gradient is the gradient.  It was derived by hand, and every result
;;      below is downstream of it, so it is checked against central finite
;;      differences on every parameter block before anything else runs.  A
;;      wrong gradient does not crash; it converges somewhere else and reports
;;      a number.
;;
;;   2. The invariants hold where they are claimed and fail where they are not.
;;      The cutpoints are increasing by construction, so the probabilities are
;;      non-negative for parameters the optimiser can actually reach -- that is
;;      tested at extremes.  Unimodality is NOT guaranteed, the commentary says
;;      so, and there is a test that constructs the bimodal case rather than
;;      leaving the disclaimer unexamined.
;;
;;   3. The ordinal structure earns its keep -- on synthetic data where the
;;      structure is known to be present, against a nominal head on the same
;;      features with the same optimiser budget.  That is a test of the
;;      implementation, not a preview of the real result, and it is labelled
;;      that way: data generated by an ordinal process is exactly where an
;;      ordinal model should win, and winning there proves only that the code
;;      exploits structure when structure is there.
;;
;; Runs on synthetic features plus the dataset file.  No donor, no GPU.

;;; Code:

(require 'nso-score)
(require 'nso-types)
(require 'nso-probe)
(require 'nso-stub)
(load (expand-file-name "nso-test-helper.el"
                        (file-name-directory (or load-file-name buffer-file-name))))

(message "== score ==")

(defvar nso-t--dim1024-limit 0.05
  "The same convergence limit the probe's gate 0 applies.")

(defvar st--here (file-name-directory (or load-file-name buffer-file-name)))

;;; --- 1. the gradient is the gradient -------------------------------------

(defun st--rand-vec (rng dim &optional scale)
  (let ((v (make-vector dim 0.0)) (s (or scale 1.0)))
    (dotimes (j dim) (aset v j (* s (- (nso-rng-float rng) 0.5))))
    v))

(defun st--fd (model xs ys l2 get set eps)
  "Central difference of the loss in one scalar parameter."
  (let ((x0 (funcall get model)) (lp nil) (lm nil))
    (funcall set (+ x0 eps))
    (setq lp (nso-score-loss model xs ys l2))
    (funcall set (- x0 eps))
    (setq lm (nso-score-loss model xs ys l2))
    (funcall set x0)
    (/ (- lp lm) (* 2.0 eps))))

(let* ((rng (nso-rng 4711))
       (dim 5) (k 4) (l2 0.03) (eps 1.0e-5)
       (xs (let (out) (dotimes (_ 7) (push (st--rand-vec rng dim 2.0) out)) out))
       (ys (let (out) (dotimes (_ 7) (push (mod (nso-rng-next rng) k) out)) out))
       (model (nso-score-make dim k)))
  ;; Off the initial point: at w = 0 several derivatives are symmetric and a
  ;; sign error would survive the check.
  (let ((w (plist-get model :w)))
    (dotimes (j dim) (aset w j (- (nso-rng-float rng) 0.5))))
  (setq model (plist-put model :t -1.1))
  (let ((d (plist-get model :d)))
    (dotimes (j (length d)) (aset d j (+ 0.3 (nso-rng-float rng)))))
  (let ((g (nso-score-grad model xs ys l2)))
    (dotimes (j dim)
      (let ((want (st--fd model xs ys l2
                          (lambda (_) (aref (plist-get model :w) j))
                          (lambda (v) (aset (plist-get model :w) j v))
                          eps)))
        (nso-t-num (format "grad dw[%d] matches finite differences" j)
                   (aref (plist-get g :dw) j) want 1.0e-5)))
    (nso-t-num "grad dt matches finite differences"
               (plist-get g :dt)
               (st--fd model xs ys l2
                       (lambda (_) (plist-get model :t))
                       (lambda (v) (setq model (plist-put model :t v)))
                       eps)
               1.0e-5)
    (dotimes (j (length (plist-get model :d)))
      (let ((want (st--fd model xs ys l2
                          (lambda (_) (aref (plist-get model :d) j))
                          (lambda (v) (aset (plist-get model :d) j v))
                          eps)))
        (nso-t-num (format "grad dd[%d] matches finite differences" j)
                   (aref (plist-get g :dd) j) want 1.0e-5)))))

;;; --- 2. invariants, where they hold and where they do not ----------------

(let ((rng (nso-rng 99)))
  ;; Extremes rather than typical values: the parameterisation is supposed to
  ;; make a broken distribution unreachable, so the test goes where a penalty
  ;; would have failed.
  (let ((bad 0) (nonsum 0))
    (dotimes (_ 200)
      (let* ((k (+ 2 (mod (nso-rng-next rng) 6)))
             (model (nso-score-make 4 k))
             (x (st--rand-vec rng 4 40.0)))
        (let ((w (plist-get model :w)))
          (dotimes (j 4) (aset w j (* 30.0 (- (nso-rng-float rng) 0.5)))))
        (setq model (plist-put model :t (* 40.0 (- (nso-rng-float rng) 0.5))))
        (let ((d (plist-get model :d)))
          (dotimes (j (length d)) (aset d j (* 60.0 (- (nso-rng-float rng) 0.5)))))
        (let ((th (nso-score-cutpoints model))
              (p (nso-score-probs model x))
              (s 0.0))
          (dotimes (j (1- (length th)))
            (unless (< (aref th j) (aref th (1+ j))) (setq bad (1+ bad))))
          (dotimes (j (length p))
            (when (or (< (aref p j) 0.0) (nso-t--nan-p (aref p j)))
              (setq bad (1+ bad)))
            (setq s (+ s (aref p j))))
          (unless (< (abs (- s 1.0)) 1.0e-9) (setq nonsum (1+ nonsum))))))
    (nso-t "cutpoints strictly increasing at extreme parameters" (= bad 0)
           (format "%d violations over 200 draws" bad))
    (nso-t "distributions sum to one at extreme parameters" (= nonsum 0)
           (format "%d violations" nonsum))))

;; Noul is this head with two levels -- section 2's claim that there is one
;; architecture, checked rather than asserted.
(let* ((model (nso-score-make 3 2))
       (x (vector 0.3 -0.7 1.1)))
  (let ((w (plist-get model :w)))
    (aset w 0 0.9) (aset w 1 -0.4) (aset w 2 0.2))
  (setq model (plist-put model :t 0.35))
  (let* ((p (nso-score-probs model x))
         (f (nso-dot (plist-get model :w) x)))
    (nso-t-num "K=2 reduces to a logistic head"
               (aref p 1) (nso-sigmoid (- f 0.35)) 1.0e-12)
    (nso-t-num "K=2 has no free cutpoint beyond the first"
               (length (plist-get model :d)) 0 0.5)))

;; Unimodality is not guaranteed, and this is the reachable counterexample.
(let* ((model (nso-score-make 2 4)))
  (setq model (plist-put model :t -0.2))
  (let ((d (plist-get model :d)))
    ;; softplus(d) = 0.2: a narrow middle interval with wide tails, which puts
    ;; mass at both ends and a dip between them.
    (dotimes (j (length d)) (aset d j (log (- (exp 0.2) 1.0)))))
  (let ((p (nso-score-probs model (vector 0.0 0.0))))
    (nso-t "a fitted cutpoint spacing can make the distribution bimodal"
           (not (nso-score-unimodal-p p))
           (format "p = %s" (mapcar (lambda (v) (format "%.3f" v)) (append p nil))))
    (nso-t-num "the bimodal case still sums to one"
               (apply #'+ (append p nil)) 1.0 1.0e-12)))

(nso-t "a bell-shaped distribution is called unimodal"
       (nso-score-unimodal-p (vector 0.05 0.2 0.5 0.2 0.05)))
(nso-t "a flat distribution is called unimodal"
       (nso-score-unimodal-p (vector 0.25 0.25 0.25 0.25)))

;;; --- readouts -------------------------------------------------------------

;; The mode and the median are different answers, and the median is the one
;; that minimises absolute error.  Section 2's shared contract requires the
;; mode, so this measures what the contract costs rather than assuming it is
;; free.
(let* ((p (vector 0.45 0.30 0.25)))
  (nso-t-num "mode of a left-heavy distribution" (nso-score-mode p) 0 0.5)
  (nso-t-num "median of the same distribution" (nso-score-median p) 1 0.5)
  (nso-t-num "expected level of the same distribution"
             (nso-score-expected p) 0.80 1.0e-9)
  ;; Expected absolute error under p, for each candidate answer.
  (let ((err (lambda (a) (let ((s 0.0))
                           (dotimes (k 3) (setq s (+ s (* (aref p k) (abs (- a k))))))
                           s))))
    (nso-t-lt "the median beats the mode on expected absolute error"
              (funcall err (nso-score-median p)) (funcall err (nso-score-mode p)))))

;; max p is a poor confidence readout on an ordinal scale, and this pins why:
;; two distributions that know completely different amounts get the same
;; number.  `nso-score-answer' reports it as a placeholder, so the placeholder
;; is documented by a failing-if-changed test rather than by a comment alone.
(let ((adjacent (vector 0.0 0.5 0.5 0.0 0.0))
      (extremes (vector 0.5 0.0 0.0 0.0 0.5)))
  (nso-t-num "max p cannot tell an adjacent split from an extreme one"
             (- (apply #'max (append adjacent nil))
                (apply #'max (append extremes nil)))
             0.0 1.0e-12)
  (nso-t-lt "but their expected absolute spreads differ by a lot"
            (let ((m (nso-score-expected adjacent)) (s 0.0))
              (dotimes (k 5) (setq s (+ s (* (aref adjacent k) (abs (- k m))))))
              s)
            (let ((m (nso-score-expected extremes)) (s 0.0))
              (dotimes (k 5) (setq s (+ s (* (aref extremes k) (abs (- k m))))))
              s)))

;;; --- baselines ------------------------------------------------------------

(let* ((ys (let (out) (dotimes (i 50) (push (mod i 5) out)) out))
       (base (nso-score-constant-mae ys 5)))
  (nso-t-num "best constant answer on a balanced 5-level set is the middle"
             (plist-get base :level) 2 0.5)
  (nso-t-num "and its MAE is 1.2" (plist-get base :mae) 1.2 1.0e-9))

(nso-t-signals "MAE refuses an empty set" (lambda () (nso-score-mae nil nil)))

;;; --- 3. does the ordering earn its keep? ---------------------------------

(defvar st--dim 16)
(defvar st--cuts '(-1.5 -0.5 0.5 1.5))

(defun st--task (rng n u noise)
  "N examples whose level is which interval of ST--CUTS the latent falls in."
  (let ((xs nil) (ys nil))
    (dotimes (_ n)
      (let* ((x (st--rand-vec rng st--dim 1.0))
             (f (+ (nso-dot u x) (* noise (- (nso-rng-float rng) 0.5))))
             (lvl 0))
        (dolist (c st--cuts) (when (> f c) (setq lvl (1+ lvl))))
        (push x xs) (push lvl ys)))
    (cons (nreverse xs) (nreverse ys))))

(let* ((rng (nso-rng 20260920))
       ;; |u| chosen so the latent spans the cutpoints rather than sitting
       ;; inside one interval, which would make every level but one empty.
       (u (let ((v (st--rand-vec rng st--dim 1.0)) (s 0.0))
            (dotimes (j st--dim) (setq s (+ s (* (aref v j) (aref v j)))))
            (setq s (/ 5.2 (sqrt s)))
            (dotimes (j st--dim) (aset v j (* s (aref v j))))
            v))
       (tr (st--task rng 60 u 0.4))
       (te (st--task rng 400 u 0.4))
       (ord (nso-score-train (car tr) (cdr tr) 5 600 0.5 0.01))
       (nom (nso-score-nominal-train (car tr) (cdr tr) 5 600 0.5 0.01))
       (ord-p (mapcar (lambda (x) (nso-score-probs ord x)) (car te)))
       (nom-p (mapcar (lambda (x) (nso-score-nominal-probs nom x)) (car te)))
       (ord-s (nso-score-report ord-p (cdr te)))
       (nom-s (nso-score-report nom-p (cdr te)))
       (base (nso-score-constant-mae (cdr te) 5)))
  (nso-t-lt "the ordinal head converged (small final gradient)"
            (plist-get ord :final-gnorm) 0.05)
  (nso-t-lt "the nominal head converged too, on the same budget"
            (plist-get nom :final-gnorm) 0.05)
  (nso-t-lt "ordinal head beats the best constant answer on MAE"
            (plist-get ord-s :mae) (plist-get base :mae))
  (nso-t-gt "ordinal head beats chance accuracy" (plist-get ord-s :accuracy) 0.20)
  ;; The architectural comparison.  Written in the direction that can fail:
  ;; if imposing the ordering did not help at this sample size, this goes red
  ;; and the claim in section 2 needs revising rather than repeating.
  (nso-t-lt "ordinal beats nominal on MAE at n=60, same features and budget"
            (plist-get ord-s :mae) (plist-get nom-s :mae))
  (nso-t-lt "and it does so with a fraction of the parameters"
            (+ st--dim 4) (* 5 st--dim))
  (message "    ordinal: acc %.3f MAE %.3f | nominal: acc %.3f MAE %.3f | constant MAE %.3f"
           (plist-get ord-s :accuracy) (plist-get ord-s :mae)
           (plist-get nom-s :accuracy) (plist-get nom-s :mae)
           (plist-get base :mae)))

;; Negative control (section 4.4).  Labels shuffled, everything else identical:
;; the head must land at chance and at the constant-answer MAE.  A pipeline
;; that scores above chance here is measuring its own plumbing.
(let* ((rng (nso-rng 5150))
       (u (st--rand-vec rng st--dim 5.0))
       (tr (st--task rng 120 u 0.4))
       (te (st--task rng 400 u 0.4))
       (shuffled (let ((ys (copy-sequence (cdr tr))))
                   (mapcar (lambda (_) (mod (nso-rng-next rng) 5)) ys)))
       (ord (nso-score-train (car tr) shuffled 5 600 0.5 0.01))
       (s (nso-score-report (mapcar (lambda (x) (nso-score-probs ord x)) (car te))
                            (cdr te)))
       (base (nso-score-constant-mae (cdr te) 5)))
  (nso-t "negative control: accuracy at chance on shuffled labels"
         (< (plist-get s :accuracy) 0.33)
         (format "acc %.3f, chance 0.200" (plist-get s :accuracy)))
  (nso-t "negative control: MAE no better than the constant answer"
         (> (plist-get s :mae) (* 0.85 (plist-get base :mae)))
         (format "MAE %.3f against constant %.3f"
                 (plist-get s :mae) (plist-get base :mae))))

;;; --- at the dimension the encoder actually produces ------------------------
;;
;; The case that was missing, and its absence cost an encode run.  Everything
;; above fits at dim 16 and the GPU-free smoke fitted at dim 64; the encoder
;; produces dim 1024, where a standardised feature vector has norm about 32
;; and the fixed step of 0.5 that suits dim 16 overshoots on every iteration.
;; The first real run came back with a gradient norm of 4.79 against a limit
;; of 0.05 and a held-out NLL of 9.66, and its pre-registered gate 0 voided
;; the comparison.
;;
;; This is the fourth time a step size chosen against synthetic data met a
;; real scale and lost, and the third time a synthetic suite stayed green
;; while the shipped setting failed.  The scale was matched in the smoke --
;; RMS 4, deliberately -- and the DIMENSION was not, which is half a lesson
;; applied.  So the suite now fits at the real dimension, with the real
;; training-split size, and it is slow on purpose.

(let* ((rng (nso-rng 1024))
       (dim 1024) (n 165) (k 5)
       (u (st--rand-vec rng dim 1.0))
       (xs nil) (ys nil))
  ;; Scale the planted direction so the latent spans the levels rather than
  ;; sitting inside one of them.
  (let ((s 0.0))
    (dotimes (j dim) (setq s (+ s (* (aref u j) (aref u j)))))
    (setq s (/ 5.2 (sqrt s)))
    (dotimes (j dim) (aset u j (* s (aref u j)))))
  (dotimes (_ n)
    (let* ((x (st--rand-vec rng dim 1.0))
           (f (nso-dot u x))
           (lvl 0))
      (dolist (c st--cuts) (when (> f c) (setq lvl (1+ lvl))))
      (push x xs) (push lvl ys)))
  (setq xs (nreverse xs) ys (nreverse ys))
  (let* ((std (nso-standardizer xs))
         (sx (mapcar (lambda (v) (nso-standardize std v)) xs))
         (norm (let ((s 0.0)) (dotimes (j dim) (setq s (+ s (* (aref (car sx) j)
                                                               (aref (car sx) j)))))
                    (sqrt s)))
         ;; The probe's budget, not a shorter one.  A fixture that stands in
         ;; for the real fit has to use the real dimension AND the real step
         ;; count: at 150 steps this head is still at |g| 6.3e-02 and would
         ;; look like a failure, at 600 it reaches 3.0e-03.  Slow on purpose.
         (ord (nso-score-train sx ys k 600 0.5 0.01))
         (nom (nso-score-nominal-train sx ys k 600 0.5 0.01))
         (start (nso-score-loss (nso-score-make dim k) sx ys 0.01)))
    (nso-t-gt "a standardised dim-1024 feature vector has the norm that broke it"
              norm 25.0)
    (nso-t-lt "the ordinal head converges at dim 1024"
              (plist-get ord :final-gnorm) nso-t--dim1024-limit)
    (nso-t-lt "the nominal head converges at dim 1024"
              (plist-get nom :final-gnorm) nso-t--dim1024-limit)
    (nso-t-lt "and the ordinal loss went down rather than up"
              (plist-get ord :final-loss) start)
    (message "    dim 1024: |x| %.1f, ordinal |g| %.2e loss %.4f (from %.4f), nominal |g| %.2e"
             norm (plist-get ord :final-gnorm) (plist-get ord :final-loss)
             start (plist-get nom :final-gnorm))))

;;; --- calibration on the ordinal scale ------------------------------------

(let* ((rng (nso-rng 777))
       (margins nil) (ys nil))
  ;; Calibrated by construction: labels drawn from the distribution the
  ;; margins imply.  A temperature fitted here should come back near one.
  (dotimes (_ 600)
    (let* ((f (* 3.0 (- (nso-rng-float rng) 0.5)))
           (z (vector (- -1.5 f) (- -0.5 f) (- 0.5 f) (- 1.5 f)))
           (p (nso-score-probs-from-margins z))
           (u (nso-rng-float rng))
           (acc 0.0) (lab 4) (done nil))
      (dotimes (k 5)
        (unless done
          (setq acc (+ acc (aref p k)))
          (when (>= acc u) (setq lab k done t))))
      (push z margins) (push lab ys)))
  (setq margins (nreverse margins) ys (nreverse ys))
  (let ((fit (nso-score-temperature-fit margins ys)))
    (nso-t "temperature on a calibrated-by-construction model lands near one"
           (and (> (plist-get fit :temperature) 0.75)
                (< (plist-get fit :temperature) 1.35))
           (format "T = %.3f" (plist-get fit :temperature)))
    (nso-t "and it is not resting on a bound"
           (not (plist-get fit :saturated))))
  ;; An overconfident model: margins divided by 4 before the labels are drawn
  ;; would be underconfident, so sharpen instead -- multiply the margins'
  ;; inverse.  Scaling by 1/4 makes the reported distribution four times too
  ;; sharp for the labels it produced, and the fit must find T > 1.
  (let* ((sharp (nso-score-scale-margins margins 0.25))
         (fit (nso-score-temperature-fit sharp ys)))
    (nso-t-gt "an overconfident model needs a temperature above one"
              (plist-get fit :temperature) 2.0)
    (nso-t-lt "and recalibrating it recovers most of the lost NLL"
              (plist-get fit :nll-after) (plist-get fit :nll-before)))
  ;; The property that does NOT carry over from the binary head.  This file
  ;; first claimed an ordinal temperature could not change an answer, by
  ;; analogy with the binary one, and the claim is false: each probability is
  ;; an increment of sigma across an interval, and rescaling every interval
  ;; moves which one collects the most mass.  The test is kept in the form
  ;; that caught it.
  (let* ((z (vector -10.0 -3.0 0.1 0.2))
         (at (lambda (temp)
               (nso-score-mode
                (nso-score-probs-from-margins
                 (car (nso-score-scale-margins (list z) temp)))))))
    (nso-t-num "at T=1 these margins report level 2" (funcall at 1.0) 2 0.5)
    (nso-t-num "at T=5 the same margins report level 4" (funcall at 5.0) 4 0.5)
    (nso-t "so an ordinal temperature CAN change the reported level"
           (/= (funcall at 1.0) (funcall at 5.0))
           "the binary one cannot; runs must report accuracy on both sides")))

;;; --- out-of-fold margins ------------------------------------------------
;;
;; The reason this exists is P1's: a temperature fitted on margins the head has
;; already separated comes back sharpening a model that is about to meet data
;; it has not seen.  On noise features with random labels the head memorises
;; the training split, so an in-fold temperature wants MORE confidence and an
;; out-of-fold one wants less.  The gap between them is the leak, and this
;; measures it rather than asserting the fix works.

(let* ((rng (nso-rng 31337))
       (dim 40) (k 5) (ngroups 15)
       (items nil) (ys nil) (groups nil))
  (dotimes (g ngroups)
    (dotimes (_ 3)
      (push (st--rand-vec rng dim 1.0) items)
      (push (mod (nso-rng-next rng) k) ys)
      (push (1+ g) groups)))
  (setq items (nreverse items) ys (nreverse ys) groups (nreverse groups))
  (let* ((feat (lambda (_a _b) #'identity))
         (oof (nso-score-oof-margins items ys groups feat k 3 400 0.5 0.01))
         (std (nso-standardizer items))
         (head (nso-score-train (mapcar (lambda (v) (nso-standardize std v)) items)
                                ys k 400 0.5 0.01))
         (infold (mapcar (lambda (v) (nso-score-margins head (nso-standardize std v)))
                         items))
         (t-oof (plist-get (nso-score-temperature-fit oof ys) :temperature))
         (t-in (plist-get (nso-score-temperature-fit infold ys) :temperature)))
    (nso-t-num "out-of-fold margins come back one per item"
               (length oof) (length items) 0.5)
    (nso-t "each is a K-1 vector, increasing"
           (let ((ok t))
             (dolist (z oof)
               (unless (= (length z) (1- k)) (setq ok nil))
               (dotimes (j (- k 2))
                 (unless (< (aref z j) (aref z (1+ j))) (setq ok nil))))
             ok))
    (nso-t-gt "and they need a flatter temperature than the in-fold ones"
              t-oof t-in)
    (message "    T out-of-fold %.2f against in-fold %.2f" t-oof t-in)))

;;; --- calibration for the head Score actually ships -------------------------
;;
;; The nominal head won gate 2, so its calibration is the one that matters.
;; Three things are checked, and the first is the one the ordinal temperature
;; failed: a multiclass temperature divides every logit by the same positive
;; number, which preserves their order, so it CANNOT change the answer.  That
;; is the property section 4.2 assumes when it calls temperature free, and it
;; is checked here rather than assumed because assuming it by analogy is
;; exactly how the ordinal head's commentary came to be wrong.

(let* ((rng (nso-rng 606))
       (k 5)
       (logits nil) (ys nil))
  ;; Calibrated by construction: labels drawn from the distribution the logits
  ;; report, so an honest temperature is 1.
  (dotimes (_ 800)
    (let* ((z (let ((v (make-vector k 0.0)))
                (dotimes (j k) (aset v j (* 4.0 (- (nso-rng-float rng) 0.5))))
                v))
           (p (nso-softmax-vec z))
           (u (nso-rng-float rng))
           (acc 0.0) (lab (1- k)) (done nil))
      (dotimes (j k)
        (unless done
          (setq acc (+ acc (aref p j)))
          (when (>= acc u) (setq lab j done t))))
      (push z logits) (push lab ys)))
  (setq logits (nreverse logits) ys (nreverse ys))
  ;; 1. answer preservation, which is the whole reason temperature is reached
  ;;    for first.
  ;;
  ;; The property holds, and getting here took a detour worth recording.  The
  ;; first version of this check reported 19 of 3200 answers moved, and the
  ;; conclusion drawn was that the guarantee needed weakening to "no pair
  ;; REVERSES, but a tie can break the other way".  That conclusion was wrong:
  ;; the 19 came from `nso-argmax', which was seeded at -1.0 -- below every
  ;; probability, which is the input its name promises, and above many a logit.
  ;; Handed five logits that were all below -1.0, it returned index 0 whatever
  ;; they said.  The helper is fixed and the count is zero.
  ;;
  ;; The lesson is not about argmax.  A measurement that disagrees with simple
  ;; mathematics is first evidence about the measurement, and the reflex to
  ;; weaken the claim until it matches the number is how a real defect gets
  ;; written into a docstring as a caveat.
  (let ((reversed 0) (moved 0))
    (dolist (temp '(0.1 0.3 2.0 9.0))
      (let ((scaled (nso-score-nominal-scale logits temp))
            (a logits))
        (dolist (z scaled)
          (let* ((was (nso-argmax (append (car a) nil)))
                 (now (nso-argmax (append z nil))))
            (unless (= was now)
              (setq moved (1+ moved))
              (unless (= (aref z was) (aref z now))
                (setq reversed (1+ reversed)))))
          (setq a (cdr a)))))
    (nso-t "a multiclass temperature reverses no pair of logits" (= reversed 0)
           (format "%d reversals of %d" reversed (* 4 (length logits))))
    (nso-t "and so changes no answer at all" (= moved 0)
           (format "%d moved of %d" moved (* 4 (length logits)))))
  ;; 2. an honest fit on an honest model
  (let ((fit (nso-score-nominal-temperature-fit logits ys)))
    (nso-t "temperature on a calibrated-by-construction softmax lands near one"
           (and (> (plist-get fit :temperature) 0.8)
                (< (plist-get fit :temperature) 1.25))
           (format "T = %.3f" (plist-get fit :temperature)))
    (nso-t "and is not resting on a bound" (not (plist-get fit :saturated))))
  ;; 3. it can see an overconfident model, in the direction that can fail
  (let* ((sharp (nso-score-nominal-scale logits 0.25))
         (fit (nso-score-nominal-temperature-fit sharp ys)))
    (nso-t-gt "a 4x-overconfident softmax needs a temperature above one"
              (plist-get fit :temperature) 2.5)
    (nso-t-lt "and recalibrating recovers NLL"
              (plist-get fit :nll-after) (plist-get fit :nll-before))))

;; Out of fold, same leak check as the ordinal path: on noise with random
;; labels the head memorises its training split, so an in-fold temperature
;; asks for more confidence and an out-of-fold one asks for less.
(let* ((rng (nso-rng 6060))
       (dim 40) (k 5) (ngroups 15)
       (items nil) (ys nil) (groups nil))
  (dotimes (g ngroups)
    (dotimes (_ 3)
      (push (st--rand-vec rng dim 1.0) items)
      (push (mod (nso-rng-next rng) k) ys)
      (push (1+ g) groups)))
  (setq items (nreverse items) ys (nreverse ys) groups (nreverse groups))
  (let* ((feat (lambda (_a _b) #'identity))
         (oof (nso-score-nominal-oof-logits items ys groups feat k 3 400 0.5 0.01))
         (std (nso-standardizer items))
         (head (nso-score-nominal-train
                (mapcar (lambda (v) (nso-standardize std v)) items)
                ys k 400 0.5 0.01))
         (infold (mapcar (lambda (v) (nso-score-nominal-logits
                                      head (nso-standardize std v)))
                         items))
         (t-oof (plist-get (nso-score-nominal-temperature-fit oof ys) :temperature))
         (t-in (plist-get (nso-score-nominal-temperature-fit infold ys) :temperature)))
    (nso-t-num "out-of-fold logits come back one per item"
               (length oof) (length items) 0.5)
    (nso-t-gt "and need a flatter temperature than the in-fold ones" t-oof t-in)
    (message "    nominal T out-of-fold %.2f against in-fold %.2f" t-oof t-in)))

;;; --- the typed answer -----------------------------------------------------

(let* ((levels '("ruled out" "unlikely" "uncertain" "likely" "certain"))
       (q (nso-make-score "how committed?" levels))
       (model (nso-score-make 3 5))
       (x (vector 0.4 -0.2 0.9)))
  (let ((w (plist-get model :w)))
    (aset w 0 1.2) (aset w 1 0.3) (aset w 2 -0.8))
  (let ((a (nso-score-answer model x levels)))
    (nso-t-green "a Score answer passes the type gate" (nso-type-gate q a))
    (nso-t "the answer names a declared level"
           (and (member (plist-get a :score) levels) t))
    (nso-t-num "it reports one probability per level"
               (length (plist-get a :probabilities)) 5 0.5))
  ;; The gate must reject a median readout, because section 2 requires the
  ;; argmax.  This is a decision, not an oversight, and it is pinned so that a
  ;; later change to the contract has to change a test that says what it cost.
  (let* ((p (vector 0.45 0.30 0.25 0.0 0.0))
         (a (list :score (nth 1 levels)     ; the median, not the mode
                  :probabilities (let ((out nil) (i 0))
                                   (dolist (n levels)
                                     (push (cons n (aref p i)) out)
                                     (setq i (1+ i)))
                                   (nreverse out))
                  :confidence 0.45)))
    (let ((g (nso-type-gate q a)))
      (nso-t-red "the gate rejects a median readout under the argmax contract" g)
      ;; For the argmax reason -- not because it could not find the answer at
      ;; all.  Before `nso--answer-key' existed this rejection was green while
      ;; the gate was reading the wrong key, so the reason is now part of the
      ;; check rather than left to the eye.
      (nso-t "and rejects it for the argmax reason, not a missing key"
             (and (string-match-p "argmax" (car (plist-get g :violations))) t)
             (car (plist-get g :violations)))))
  (let ((a (list :score "somewhat likely"
                 :probabilities (mapcar (lambda (n) (cons n 0.2)) levels)
                 :confidence 0.2)))
    (let ((g (nso-type-gate q a)))
      (nso-t-red "the gate rejects a level outside the legend" g)
      (nso-t "naming the offending level rather than nil"
             (and (string-match-p "somewhat likely" (car (plist-get g :violations))) t)
             (car (plist-get g :violations))))))

;;; --- the dataset itself ---------------------------------------------------
;;
;; The data file is generated, and a generated file is exactly the kind that
;; gets hand-edited once and never checked again.  These re-derive the
;; properties the run depends on from the file on disk rather than trusting
;; the generator that wrote it.

(let* ((path (expand-file-name "../data/score-commitment.eld" st--here))
       (form (with-temp-buffer (insert-file-contents path) (read (buffer-string))))
       (rows (append (plist-get form :examples) nil))
       (k (length (plist-get form :levels)))
       (counts (make-vector k 0))
       (texts (make-hash-table :test 'equal))
       (dups 0)
       (scenarios (make-hash-table :test 'eql)))
  (dolist (r rows)
    (aset counts (plist-get r :level) (1+ (aref counts (plist-get r :level))))
    (if (gethash (plist-get r :text) texts) (setq dups (1+ dups))
      (puthash (plist-get r :text) t texts))
    (puthash (plist-get r :scenario) t scenarios))
  (nso-t-num "dataset has 240 examples" (length rows) 240 0.5)
  (nso-t-num "over 16 scenarios" (hash-table-count scenarios) 16 0.5)
  (nso-t "no duplicate sentences" (= dups 0) (format "%d duplicates" dups))
  (nso-t "levels are exactly balanced"
         (let ((ok t)) (dotimes (i k) (unless (= (aref counts i) 48) (setq ok nil))) ok)
         (format "%s" (append counts nil)))
  (nso-t-num "so the majority baseline is 0.200"
             (/ (float (aref counts 0)) (length rows)) 0.200 1.0e-9)
  (nso-t-num "and the best constant answer costs 1.200 MAE"
             (plist-get (nso-score-constant-mae
                         (mapcar (lambda (r) (plist-get r :level)) rows) k)
                        :mae)
             1.200 1.0e-9)
  ;; The property the hard subset exists for, re-derived from the file rather
  ;; than trusted from the generator: every hard sentence has a partner in its
  ;; own scenario with an identical SET of words.  Two inputs a bag-of-words
  ;; model cannot tell apart must get the same answer, so the pairing puts a
  ;; ceiling on what any such model can score here -- of any capacity, which
  ;; is the point.  The first version of this dataset claimed the same thing
  ;; from a check that looked only at which negation words were present, and a
  ;; five-way softmax scored 0.800 on the subset it produced.
  (let ((groups (make-hash-table :test 'equal))
        (unpaired 0) (right 0.0) (gap 0.0) (hard-n 0))
    (dolist (r rows)
      (when (plist-get r :hard)
        (let* ((bag (sort (delete-dups
                           (split-string (downcase (plist-get r :text))
                                         "[^a-z]+" t))
                          #'string<))
               (key (list (plist-get r :scenario) bag)))
          (puthash key (cons r (gethash key groups)) groups)
          (setq hard-n (1+ hard-n)))))
    (maphash (lambda (_k members)
               (if (/= (length members) 2)
                   (setq unpaired (1+ unpaired))
                 (let ((a (plist-get (nth 0 members) :level))
                       (b (plist-get (nth 1 members) :level)))
                   (setq right (+ right (if (= a b) 2.0 1.0))
                         gap (+ gap (abs (- a b)))))))
             groups)
    (nso-t "every hard sentence has a bag-identical partner" (= unpaired 0)
           (format "%d unpaired groups of %d" unpaired (hash-table-count groups)))
    (nso-t-num "which caps any bag-of-words model at 0.600 accuracy"
               (/ right hard-n) 0.600 1.0e-9)
    (nso-t-num "and floors it at the constant answer's 1.200 MAE"
               (/ gap hard-n) 1.200 1.0e-9))
  ;; Splitting by scenario must leave both sides non-empty and disjoint in
  ;; scenario, which is the invariant the probe relies on.
  (let ((tr 0) (te 0) (overlap nil) (te-scen (make-hash-table :test 'eql)))
    (dolist (r rows)
      (if (= 0 (mod (plist-get r :scenario) 3))
          (progn (setq te (1+ te)) (puthash (plist-get r :scenario) t te-scen))
        (setq tr (1+ tr))))
    (dolist (r rows)
      (when (and (/= 0 (mod (plist-get r :scenario) 3))
                 (gethash (plist-get r :scenario) te-scen))
        (setq overlap t)))
    (nso-t "splitting by scenario leaves both sides populated"
           (and (> tr 0) (> te 0)) (format "%d train / %d held-out" tr te))
    (nso-t "and no scenario appears on both sides" (not overlap))))

(nso-t-done "score")

;;; score-test.el ends here
